services:
  diarydb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: DiaryDb
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TMC5Vs2c2N6l!